// To compile the Executable directly first you need
// to include the program CalcProg into CalcRegMyProg.h
//generated by progcoder
//use as follow
// progcoder CalcProg.txt >CalcRegMyProg.h
//then set #define CalcRegSoftware as comment to remove this definition
//compile -> mk
//To compile the software CalcReg just remove comment//
//the definition below is then set 

#define CalcRegSoftware 1


#define XBtn 10   //gauche du groupe de buttons
#define YBtn 10   //haut

#define WBtn 120 //deplacement d'un bouton
#define HBtn 25 // deplacement Y d'un bouton

#define BtnWdth 115 //largeur de bouton
#define BtnHght 20 // hauteur de bouton

#define DrawZoneXChg 320 
#define DrawZoneYChg 90
#define DrawZoneHChg  100 //50
#define DrawZoneWChg  340 //340

#define START_TEXT "Set Volume down to 10%\nUse of Headphone works better\nDo not listen at high volumes set.\n+/- to changes freq. then Play."
 
